site_name: ETHDenver 2025 Notes
site_description: Collection of presentation notes from ETHDenver 2025
site_author: KupiaSec

theme:
  name: material  # or your chosen theme
  logo: assets/logo.png
  favicon: assets/favicon.ico
  custom_dir: docs/overrides
  palette:
    primary: indigo
  features:
    - content.code.copy
    - header.autohide
    - navigation.top
    - navigation.footer

docs_dir: docs

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

nav:
  - About: index.md
  - ...

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KupiaSec
    - icon: fontawesome/brands/twitter
      link: https://x.com/KupiaSecurity

extra_css:
  - stylesheets/extra.css

copyright: "All content belongs to respective presenters"